export const COSMOS_MODULE_OPTIONS = Symbol("COSMOS_MODULE_OPTIONS");
export const COSMOS_MODEL_METADATA = Symbol("COSMOS_MODEL_METADATA");
export const COSMOS_PARTITION_KEY_METADATA = Symbol(
  "COSMOS_PARTITION_KEY_METADATA",
);
export const COSMOS_RELATIONS_METADATA = Symbol("COSMOS_RELATIONS_METADATA");
